name: chakra
description: "Chakra VPN - Professional VPN Client"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  google_fonts: ^6.2.1
  flutter_webrtc: ^0.12.3
  socket_io_client: ^2.0.3+1
  connectivity_plus: ^6.0.0
  flutter_background_service: ^5.0.0
  lottie: ^3.0.0
  flutter_background_service_android: ^6.3.1
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/chakra.png

  fonts:
    - family: SourGummy
      fonts:
        - asset: assets/SourGummy-Medium.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/chakra.png"
  min_sdk_android: 21
  remove_alpha_ios: true
